"""One-line page descriptions for the page menu (spec 5.3): first sentence of each page's About text."""

from __future__ import annotations

PAGE_DESCRIPTIONS: dict[str, str] = {
    '/': 'Compare configured instruments using the same local score evidence.',
    '/portfolio': 'Explore holdings and allocation scenarios from local portfolio inputs.',
    '/portfolio-optimiser': 'Test candidate weights against the displayed constraints and evidence.',
    '/signals': 'Review canonical score components, evidence gates and reasons for a signal state.',
    '/strategy-builder': 'Combine supported research features into a strategy template.',
    '/screener': 'Filter the loaded fundamentals evidence.',
    '/comparison': 'Compare aligned instruments using their displayed dates, horizons and canonical score fields.',
    '/stock-research': 'Inspect statement-based profitability, balance-sheet, valuation and sector evidence.',
    '/risk': 'Review portfolio exposure, volatility, drawdown, liquidity and cost evidence.',
    '/stress-lab': 'Change explicit scenario assumptions to see how evidence responds.',
    '/etf': 'Inspect fund identity, holdings, adjusted-price, liquidity and attribution evidence.',
    '/backtests': 'Read historical results together with the selected universe, dates, benchmark, rebalance and cost assumptions.',
    '/chatgpt': 'Review local audit commentary and its linked evidence.',
    '/providers': 'Check provider capability, local cache, freshness, terms and failure status.',
    '/evidence': 'Trace displayed facts to their source, observation date, retrieval time and authority.',
    '/filings': 'Review filing identity, period, publication and retrieval details.',
    '/etf-disclosures': 'Inspect available fund disclosures and their dates.',
    '/news-context': 'Use news as dated context, with its source and mapping confidence.',
    '/data-models': 'Compare model tasks, availability, versions, validation and licence metadata.',
    '/forecasts': 'Review forecast dates, horizons, matured outcomes, error measures and interval coverage.',
    '/training-centre': 'Inspect recorded experiments, run status, metrics, artefacts and human approval.',
    '/feature-catalogue': "Read each feature's meaning, source, availability and supported use before selecting it.",
    '/catalogue': 'Use the local dataset catalogue to check coverage, dates, source and licence notes.',
    '/macro': 'Read macro observations with their release/vintage dates and units.',
    '/settings': 'Review local preferences and release metadata.',
    '/diagnostics': 'Use diagnostics to inspect configuration and local service state.',
    '/errors': 'Follow the named recovery guidance and keep the original files and logs intact.',
    '/data-health': 'Check freshness, coverage, conflicts and unsupported fields before analysis.',
    '/universe': 'Inspect configured membership, classification and coverage evidence.',
    '/onboarding': 'Set up local preferences and supported data paths.',
    '/what-changed': 'Compare dated evidence, source revisions, formula versions and policy changes between runs.',
    '/instrument': "Inspect one instrument's evidence, score components, history and limitations.",
    '/import-export': 'Review file identity, licence, mappings and dry-run warnings before importing.',
    '/system-map': 'Use the map to understand which policy and evidence gates control a capability.',
    '/help': 'Use the glossary for score, data and authority terms.',
    '/decision-journal': 'Record your own decision, alternatives and rationale beside the evidence snapshot.',
    '/forward-evidence': 'Review frozen decisions against outcomes only after their horizons mature.',
    '/jobs': 'Check local job status, progress and recorded errors.',
    '/operations': 'Review proposal and local paper states separately.',
    '/release-readiness': 'Read the exact gate results and their evidence scope.',
    '/roadmap': 'Use the programme map to understand implementation status and dependencies.',
    '/sectors': 'Compare sectors and countries on a globe and a map using one return basis.',
}
